#!/system/bin/sh

# BurpSuiteCert Module for KSU/ksu-next - Installs CA certificates
# NOTE: This file is a template. It should NOT be edited manually.
# Users must run generate-module.sh to create a proper module with their certificate.

MODDIR=${0%/*}
MODNAME="BurpSuiteCert"

log_info() {
    echo "[BurpSuiteCert] $1"
}

log_error() {
    echo "[BurpSuiteCert ERROR] $1" >&2
}

log_error "ERROR: This is a template file!"
log_error "This file should be auto-generated by generate-module.sh"
log_error "Please run: bash generate-module.sh --cert your-certificate.der"
log_error "Then use the generated BurpSuiteCert.zip file"

exit 1
